services:

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - tamiyochi-db:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    tty: true
    environment:
      MYSQL_DATABASE: pbkk
      MYSQL_ROOT_PASSWORD: tamiyochi 
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 10s
      retries: 5

  tamiyochi-laravel:
    image: lyfesan/tamiyochi-laravel
    restart: always
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - tamiyochi-php:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
  
  webserver:
    image: nginx
    container_name: nginx-webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - tamiyochi-php:/var/www/html
    depends_on:
      - mysql
      - tamiyochi-laravel

volumes:
  tamiyochi-db:
    driver: local
  tamiyochi-php:
    driver: local