name: ci/cd server 

on: 
  push:
    branches: 
    - 'main'

jobs:
  docker_build_push:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Build and push
          uses: docker/build-push-action@v5
          with:   
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tamiyochi-laravel:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max

  server_deploy:
    needs: docker_build_push
    runs-on: ubuntu-latest

    steps:
      - name: Pull github code and redeploy docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd tamiyochi-laravel
            git pull --no-edit
            docker compose down
            docker pull lyfesan/tamiyochi-laravel
            docker compose up -d


